### ISSUE TITLE
Can't received messages with CAP version 2.5.1

### ISSUE THREAD

**Issue by yang-xiaodong** [yang-xiaodong/Savorboard.CAP.InMemoryMessageQueue#1]
**Issue https://github.com/dotnetcore/CAP/issues/370 copies**

It can not receive message by `UseInMemoryMessageQueue`

``` cs
// Startup.cs
...... 
            services.AddTransient<NBMeterDataArrivedIntegrationEventHandler>();
            services.AddCap(x => 
            {
                x.UseInMemoryStorage();
                x.UseInMemoryMessageQueue();
                x.UseDashboard();
            });
```

``` cs
// NBMeterDataArrivedIntegrationEventHandler.cs

    public class NBMeterDataArrivedIntegrationEventHandler : ICapSubscribe
    {
       ......

        [CapSubscribe(nameof(NBMeterDataArrivedIntegrationEvent))]
        public async Task HandleAsync(NBMeterDataArrivedIntegrationEvent @event)
        {
            _logger.LogInformation("######## handle data arrived event ########");
           ......
        }
    }
```

![Subscribers](https://user-images.githubusercontent.com/6382133/61604181-0e247e80-ac73-11e9-8411-654aab19350f.png)

![Published messages](https://user-images.githubusercontent.com/6382133/61604187-12509c00-ac73-11e9-9d2a-73d9e651288b.png)

![Received Messages](https://user-images.githubusercontent.com/6382133/61604270-6c516180-ac73-11e9-99b3-d1389fb1e25f.png)

**Comment by yang-xiaodong** [comment]
Hello @chinaq, 

This is a bug, we have already fixed in v2.5.1, You'll see the new nuget package in a few minutes

**Comment by chinaq** [comment]
It works. Thanks.

**Comment by captmomo** [comment]
I can't seem to use the extension method UseInMemoryMessageQueue(); I have installed the 2 nuget packages. Any help is appreciated!
