### ISSUE TITLE
CAP 更新到 8.2.0 后 报 Create 未实现

### ISSUE THREAD

**Issue by Qiulin-Git** [yang-xiaodong/Savorboard.CAP.InMemoryMessageQueue#10]
Method 'Create' in type 'Savorboard.CAP.InMemoryMessageQueue.InMemoryConsumerClientFactory' from assembly 'Savorboard.CAP.InMemoryMessageQueue, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

**Comment by yang-xiaodong** [comment]
Version 8.2.0 is relased to nuget in a few minutes ago.
