### ISSUE TITLE
Exception when there is no subscriber

### ISSUE THREAD

**Issue by rickizud** [yang-xiaodong/Savorboard.CAP.InMemoryMessageQueue#12]
DotNetCore.CAP.Internal.PublisherSentFailedException: Cannot find the corresponding group for [name]. Have you subscribed?
 ---> System.InvalidOperationException: Cannot find the corresponding group for DeliveryOrderPackedEvent. Have you subscribed?
   at Savorboard.CAP.InMemoryMessageQueue.InMemoryQueue.Send(TransportMessage message)
   at Savorboard.CAP.InMemoryMessageQueue.InMemoryMqTransport.SendAsync(TransportMessage message)
   --- End of inner exception stack trace ---
   
   Is there a way to not throwing exception if there is no subscriber ?

**Comment by yang-xiaodong** [comment]
InMemory Queue is only works for the current app process, Why send a message without subscription?
