### ISSUE TITLE
MsSQL to gRPC transport

### ISSUE THREAD

**Issue by Alex-ttt** [yang-xiaodong/Savorboard.CAP.InMemoryMessageQueue#9]
Hello!

I want to support sending messages via gRPC. I'm using the MS SQL server as storage, but for transport purposes, I want to have my own code that sends gRPC a request. Is it possible to achieve this using a library, or is there a need for a custom implementation on top of it? In the second case, what things need to be considered to ensure that the sending occurs reliably? Is it possible to reuse some existing classes for this?

**Comment by yang-xiaodong** [comment]
Hi,
The message model of gRPC is Request-Response which is similar to HTTP. The message queue-based transport is Fire-And-Forgot, so essentially this is for a different system architecture.
